---
abstract: 'adds the zilla object and the logger to your bundles'
author:
  - 'Sven Kirmess <sven.kirmess@kzone.ch>'
build_requires:
  Dist::Zilla::Role::PluginBundle::Easy: '0'
  Moose: '0'
  Test::DZil: '0'
  Test::More: '0.88'
  Test::TempDir::Tiny: '0'
  lib: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.022, CPAN::Meta::Converter version 2.150010'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Role-PluginBundle-Zilla
no_index:
  directory:
    - t
    - xt
provides:
  Dist::Zilla::Role::PluginBundle::Zilla:
    file: lib/Dist/Zilla/Role/PluginBundle/Zilla.pm
    version: '0.001'
requires:
  Dist::Zilla::Role::PluginBundle: '0'
  List::Util: '0'
  Moose::Role: '0'
  Moose::Util::TypeConstraints: '0'
  Scalar::Util: '0'
  namespace::autoclean: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/skirmess/Dist-Zilla-Role-PluginBundle-Zilla/issues
  homepage: https://github.com/skirmess/Dist-Zilla-Role-PluginBundle-Zilla
  repository: https://github.com/skirmess/Dist-Zilla-Role-PluginBundle-Zilla.git
version: '0.001'
x_generated_by_perl: v5.24.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: BSD-2-Clause-FreeBSD
